[package]
name = "ludii"
version = "0.1.0"
edition = "2021"
description = "Ludii Language support"
license = "MIT OR Apache-2.0"

[dependencies]
game-core = { path = "../games/game-core" }

[dev-dependencies]
game-ttt = { path = "../games/ttt" }
game-ttt-gen = { path = "../games/ttt-gen" }
mcts = { path = "../mcts" }

[lints]
workspace = true
