[package]
name = "mcts"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "mcts"
path = "src/lib.rs"

[[bin]]
name = "mcts"
path = "demo/main.rs"

[dependencies]
nimlib = "0.1.1"
rand = "0.8.5"
