//! Direct comparison between `game-hex-gen` (generated by `gdl::codegen::hex` from
//! `style-c/sexpr/hex-11.gdls`, an 11x11 board) and a from-scratch hand-rolled connectivity
//! reference -- there's no existing `games/hex` crate to reuse the way `games/ttt` was reused for
//! `tests/ttt_gen_oracle.rs`, per `DESIGN.md`'s corpus notes, so [`HexOracle`] (a second copy of
//! `tests/hex_oracle.rs`'s own oracle, deliberately duplicated rather than shared -- see that
//! file's doc comment for why it avoids calling into `gdl::core::hex`/`game_core::bitboard` at
//! all) plays that role here instead. Walks both sides through `mcts::game::Game`
//! (`generate_actions`/`apply`/`is_terminal`/`winner`), the same way `tests/ttt_gen_oracle.rs`
//! exercises `games/ttt-gen`'s own `Game` impl end to end.
//!
//! This is the *only* end-to-end proof `games/hex-gen` gets: unlike
//! `games/hex3-gen` (see `tests/hex3_gen_vs_interp.rs`), it's too large for
//! `core::interp::State` (`BitBoard`-backed, capped at 64 cells) to
//! represent at all, so there's no interpreter to cross-check against --
//! [`HexOracle`] uses plain arrays and has no such cap, making it the one
//! reference this crate's multi-word `bitboard::Board` codegen branch can be
//! checked against.

use mcts::game::{Game, PlayerIndex};

const SIDE: usize = 11;
const WORDS: usize = 2;
const SITES: usize = SIDE * SIDE;

/// `game_hex_gen::Hex` is const-generic over board side (see
/// `gdl/src/codegen/hex.rs`'s doc comment) -- pin it at 11x11/2-words here, the size
/// `style-c/sexpr/hex-11.gdls` (this crate's source `.gdls`) itself uses.
type Generated = game_hex_gen::Hex<SIDE, WORDS>;

/// A from-scratch reference implementation of Hex on a `SIDE x SIDE` board -- see
/// `tests/hex_oracle.rs`'s identical [`HexOracle`] for the full doc comment; kept as a second,
/// independent copy on purpose rather than shared, so a bug in one oracle isn't silently load-
/// bearing for both comparisons.
struct HexOracle {
    occupied: [[bool; SITES]; 2],
    to_move: usize,
}

impl HexOracle {
    fn new() -> Self {
        HexOracle {
            occupied: [[false; SITES]; 2],
            to_move: 0,
        }
    }

    fn legal_moves(&self) -> Vec<usize> {
        (0..SITES)
            .filter(|&s| !self.occupied[0][s] && !self.occupied[1][s])
            .collect()
    }

    fn apply(&mut self, site: usize) {
        assert!(!self.occupied[0][site] && !self.occupied[1][site]);
        self.occupied[self.to_move][site] = true;
        self.to_move = 1 - self.to_move;
    }

    fn last_mover(&self) -> usize {
        1 - self.to_move
    }

    fn neighbors(site: usize) -> Vec<usize> {
        let row = (site / SIDE) as isize;
        let col = (site % SIDE) as isize;
        [(1, 0), (-1, 0), (0, 1), (0, -1), (1, 1), (-1, -1)]
            .into_iter()
            .filter_map(|(dr, dc)| {
                let r = row + dr;
                let c = col + dc;
                (r >= 0 && (r as usize) < SIDE && c >= 0 && (c as usize) < SIDE)
                    .then(|| r as usize * SIDE + c as usize)
            })
            .collect()
    }

    fn is_terminal(&self) -> bool {
        self.winner().is_some() || self.legal_moves().is_empty()
    }

    fn winner(&self) -> Option<usize> {
        let player = self.last_mover();
        let stones = &self.occupied[player];
        let mut visited = [false; SITES];
        for start in 0..SITES {
            if !stones[start] || visited[start] {
                continue;
            }
            let mut stack = vec![start];
            visited[start] = true;
            let mut component = Vec::new();
            while let Some(site) = stack.pop() {
                component.push(site);
                for n in Self::neighbors(site) {
                    if stones[n] && !visited[n] {
                        visited[n] = true;
                        stack.push(n);
                    }
                }
            }
            let (touches_a, touches_b) = if player == 0 {
                (
                    component.iter().any(|&s| s / SIDE == 0),
                    component.iter().any(|&s| s / SIDE == SIDE - 1),
                )
            } else {
                (
                    component.iter().any(|&s| s % SIDE == 0),
                    component.iter().any(|&s| s % SIDE == SIDE - 1),
                )
            };
            if touches_a && touches_b {
                return Some(player);
            }
        }
        None
    }
}

fn legal_sites_generated(state: &<Generated as Game>::S) -> Vec<usize> {
    let mut actions = Vec::new();
    Generated::generate_actions(state, &mut actions);
    let mut sites: Vec<usize> = actions.into_iter().map(|m| m.0 as usize).collect();
    sites.sort_unstable();
    sites
}

/// Replays `sites` through both the oracle and the generated crate move by move, asserting legal
/// moves, terminal-ness, and (as a player index) the winner agree after every move.
fn assert_agrees(sites: &[usize]) {
    let mut oracle = HexOracle::new();
    let mut generated = <Generated as Game>::S::default();

    assert_eq!(
        oracle.legal_moves(),
        legal_sites_generated(&generated),
        "initial legal moves disagree"
    );
    assert_eq!(oracle.is_terminal(), Generated::is_terminal(&generated));

    for (step, &site) in sites.iter().enumerate() {
        oracle.apply(site);
        generated = Generated::apply(generated, &game_hex_gen::Move(site as u8));

        assert_eq!(
            oracle.legal_moves(),
            legal_sites_generated(&generated),
            "legal moves disagree after move {step} (site {site})"
        );
        let oracle_terminal = oracle.is_terminal();
        let generated_terminal = Generated::is_terminal(&generated);
        assert_eq!(
            oracle_terminal, generated_terminal,
            "terminal-ness disagrees after move {step} (site {site})"
        );
        if oracle_terminal {
            assert_eq!(
                oracle.winner(),
                Generated::winner(&generated).map(|p| p.to_index()),
                "winner disagrees after move {step} (site {site})"
            );
        }
    }
}

/// `(row, col)` site indices along the top-bottom column at `col`, one per row -- P0's win
/// condition (`edges` set to row 0 / row `SIDE - 1`), connected purely via `shift_north`/
/// `shift_south`.
fn column(col: usize) -> Vec<usize> {
    (0..SIDE).map(|row| row * SIDE + col).collect()
}

/// `(row, row)` site indices, one per row -- touches col 0 (row 0) and col `SIDE - 1`
/// (row `SIDE - 1`), P1's win condition, connected via the hex-adjacent
/// `shift_northeast`/`shift_southwest` diagonal (`(row, col)` <-> `(row + 1, col + 1)`; see
/// `game_core::bitboard`'s "Hex flood fill" doc comment).
fn hex_adjacent_diagonal() -> Vec<usize> {
    (0..SIDE).map(|row| row * SIDE + row).collect()
}

/// `(row, SIDE - 1 - row)` site indices, one per row -- also touches col 0 and col `SIDE - 1`,
/// but via the *other* diagonal (`(row, col)` <-> `(row + 1, col - 1)`), which is deliberately
/// not hex-adjacent: a group along this line must NOT be reported as connected despite touching
/// both edges.
fn non_hex_adjacent_diagonal() -> Vec<usize> {
    (0..SIDE).map(|row| row * SIDE + (SIDE - 1 - row)).collect()
}

/// Alternates `p0`/`p1` starting with `p0` (matching `Position::new`'s `turn: Player::P0`),
/// stopping once either runs out -- `p0` may have one more element than `p1` (its last move
/// needs no following reply).
fn interleave(p0: &[usize], p1: &[usize]) -> Vec<usize> {
    let mut seq = Vec::new();
    for i in 0..p0.len().max(p1.len()) {
        if let Some(&s) = p0.get(i) {
            seq.push(s);
        }
        if let Some(&s) = p1.get(i) {
            seq.push(s);
        }
    }
    seq
}

/// `count` distinct sites not in `used` -- filler moves for the player who isn't the one being
/// tested, chosen not to overlap (and so not to accidentally complete) the line under test.
fn filler(used: &[usize], count: usize) -> Vec<usize> {
    (0..SITES)
        .filter(|s| !used.contains(s))
        .take(count)
        .collect()
}

#[test]
fn in_progress_two_moves() {
    assert_agrees(&[4, 0]);
}

#[test]
fn in_progress_four_moves() {
    assert_agrees(&[0, 1, 3, 5]);
}

#[test]
fn p0_wins_straight_column() {
    let p0 = column(0);
    let p1 = filler(&p0, p0.len() - 1);
    assert_agrees(&interleave(&p0, &p1));
}

#[test]
fn p1_wins_hex_adjacent_diagonal() {
    let p1 = hex_adjacent_diagonal();
    let p0 = filler(&p1, p1.len());
    assert_agrees(&interleave(&p0, &p1));
}

#[test]
fn non_hex_adjacent_diagonal_does_not_connect() {
    let p1 = non_hex_adjacent_diagonal();
    let p0 = filler(&p1, p1.len());
    assert_agrees(&interleave(&p0, &p1));
}

#[test]
fn full_board_row_major_fill() {
    assert_agrees(&(0..SITES).collect::<Vec<_>>());
}
