//! Direct comparison between `games/ttt` (hand-written) and `games/ttt-gen` (generated by
//! `gdl::codegen::rect` from `style-c/sexpr/tic-tac-toe.gdls`) -- the generated crate should pass
//! the same kind of oracle check `games/ttt` already gets. Unlike `tests/oracle.rs` (which checks
//! `style_c`'s frontend + `core::interp`'s tree-walking backend against `games/ttt`), this test
//! never touches `core::interp` at all -- both sides here are ordinary, independently-compiled
//! `mcts::game::Game` implementations, walked through the same move sequence via the `Game` trait itself
//! (`generate_actions`/`apply`/`is_terminal`/`winner`), so it also exercises the generated crate's
//! own `Game` impl end to end rather than just its `Position` methods.
//!
//! The two representations differ on purpose (`games/ttt-gen`'s doc comment): one `BitBoard` per
//! player here vs. `games/ttt`'s packed 2-bit cells, a plain zobrist hash here vs. `games/ttt`'s
//! D4-symmetry-aware one -- so this compares externally observable `Game` behavior, not internal
//! state layout.

use game_ttt::TicTacToe as HandWritten;
use game_ttt_gen::TicTacToe as Generated;
use mcts::game::{Game, PlayerIndex};

fn legal_sites_hand_written(state: &<HandWritten as Game>::S) -> Vec<usize> {
    let mut actions = Vec::new();
    HandWritten::generate_actions(state, &mut actions);
    let mut sites: Vec<usize> = actions.into_iter().map(|m| m.0 as usize).collect();
    sites.sort_unstable();
    sites
}

fn legal_sites_generated(state: &<Generated as Game>::S) -> Vec<usize> {
    let mut actions = Vec::new();
    Generated::generate_actions(state, &mut actions);
    let mut sites: Vec<usize> = actions.into_iter().map(|m| m.0 as usize).collect();
    sites.sort_unstable();
    sites
}

/// Replays `sites` through both crates move by move, asserting legal moves, terminal-ness, and
/// (encoded as a player index, since the two crates' `Player`/`Piece` types don't share a type)
/// the winner agree after every move.
fn assert_agrees(sites: &[usize]) {
    let mut hand_written = <HandWritten as Game>::S::default();
    let mut generated = <Generated as Game>::S::default();

    assert_eq!(
        legal_sites_hand_written(&hand_written),
        legal_sites_generated(&generated),
        "initial legal moves disagree"
    );
    assert_eq!(
        HandWritten::is_terminal(&hand_written),
        Generated::is_terminal(&generated)
    );

    for (step, &site) in sites.iter().enumerate() {
        hand_written = HandWritten::apply(hand_written, &game_ttt::Move(site as u8));
        generated = Generated::apply(generated, &game_ttt_gen::Move(site as u8));

        assert_eq!(
            legal_sites_hand_written(&hand_written),
            legal_sites_generated(&generated),
            "legal moves disagree after move {step} (site {site})"
        );
        let hand_written_terminal = HandWritten::is_terminal(&hand_written);
        let generated_terminal = Generated::is_terminal(&generated);
        assert_eq!(
            hand_written_terminal, generated_terminal,
            "terminal-ness disagrees after move {step} (site {site})"
        );
        // Both `Game::winner` impls panic on a non-terminal state (see `games/ttt`'s own
        // `unreachable!()` guard, which `games/ttt-gen`'s `core::interp`-mirroring
        // `Position::winner`/`Game::winner` don't need but stay compatible with) -- only
        // compare once both sides agree the game is actually over.
        if hand_written_terminal {
            assert_eq!(
                HandWritten::winner(&hand_written).map(|p| p as usize),
                Generated::winner(&generated).map(|p| p.to_index()),
                "winner disagrees after move {step} (site {site})"
            );
        }
    }
}

#[test]
fn in_progress_two_moves() {
    assert_agrees(&[4, 0]);
}

#[test]
fn in_progress_four_moves() {
    assert_agrees(&[0, 1, 3, 5]);
}

#[test]
fn p1_wins_top_row() {
    assert_agrees(&[0, 3, 1, 4, 2]);
}

#[test]
fn p2_wins_middle_row() {
    assert_agrees(&[0, 3, 1, 4, 8, 5]);
}

#[test]
fn draw() {
    // Final board (row-major):
    //   X O X
    //   X O O
    //   O X X
    assert_agrees(&[0, 4, 2, 1, 3, 6, 7, 5, 8]);
}
