//! Elaboration of [`crate::ast::moves::decision`] (Language Reference 8.1): a player's actual
//! choice among the legal moves generated by the rest of [`crate::ast::moves`].
//!
//! Only `(move Add <to>)` (8.1.4's `moveSiteType::Add`, with no `[<piece>]`, `count:`, `stack:`,
//! or `[<then>]`) is elaborated so far, since it's all [`crate::elaborate::rules::play`] needs
//! for `(move Add (to (sites Empty)))`.

use crate::ast::located::Located;
use crate::ast::moves::decision::{Decision, MoveSiteType};
use crate::elaborate::common::elaborate_to;
use crate::elaborate::{call_ident, ElaborateError};
use crate::parse::SExpr;

/// `(move Add <to>)` (8.1.4).
pub fn elaborate_decision(v: &Located<SExpr>) -> Result<Decision, ElaborateError> {
    let call = call_ident(v, "move")?;
    let mut positional = call.args.iter().filter(|a| a.name.is_none());
    let kind_arg = positional.next().ok_or_else(|| ElaborateError {
        message: "(move ...) requires a moveSiteType argument".into(),
        span: v.span,
    })?;
    let SExpr::Ident(kind) = &kind_arg.value.node else {
        return Err(ElaborateError {
            message: format!(
                "expected a moveSiteType identifier, found {:?}",
                kind_arg.value.node
            ),
            span: kind_arg.value.span,
        });
    };
    let kind = match kind.as_str() {
        "Add" => MoveSiteType::Add,
        other => {
            return Err(ElaborateError {
                message: format!("unsupported (move {other} ...) -- only Add is elaborated so far"),
                span: kind_arg.value.span,
            })
        }
    };
    let to_arg = positional.next().ok_or_else(|| ElaborateError {
        message: "(move Add ...) requires a to argument".into(),
        span: v.span,
    })?;
    let to = elaborate_to(&to_arg.value)?;
    Ok(Decision::Site {
        kind,
        piece: None,
        to,
        count: None,
        stack: None,
        then: None,
    })
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::ast::common::SiteOrRegion;
    use crate::parse::parse;

    fn parse_one(src: &str) -> Located<SExpr> {
        let mut forms = parse(src).unwrap();
        assert_eq!(forms.len(), 1);
        forms.remove(0)
    }

    #[test]
    fn move_add() {
        let Decision::Site { kind, to, .. } =
            elaborate_decision(&parse_one("(move Add (to (sites Empty)))")).unwrap()
        else {
            panic!("expected a Site decision");
        };
        assert_eq!(kind, MoveSiteType::Add);
        assert!(matches!(to.location, Some(SiteOrRegion::Region(_))));
    }

    #[test]
    fn unsupported_kind_errors() {
        assert!(elaborate_decision(&parse_one("(move Claim (to (sites Empty)))")).is_err());
    }
}
