[package]
name = "game-akron"
version = "0.1.0"
edition = "2021"
publish = false

[lib]
name = "game_akron"

[dependencies]
mcts = { path = "../../mcts" }
bitboard = { path = "../../bitboard" }
pyramid = { path = "../../pyramid" }
serde = { version = "1", features = ["derive"] }

[dev-dependencies]
rand = { version = "0.8.5", features = ["small_rng"] }

[lints]
workspace = true
