// Sylver Coinage (Conway et al., "On Numbers and Games") -- players alternately name a positive
// integer that cannot be written as a non-negative-integer combination of previously named
// numbers; whoever is forced to name 1 loses outright (naming 1 generates all of N, so it always
// ends the game). No .lud source, no board, no topology, no spatial component whatsoever -- the
// deliberate "math game" pathological case: it stresses whether Core IR's declarative layer
// means anything at all once a game has no Region/Raster/site concept to build on top of. Pro
// forma, same license as `games/tak.sc`.

game "SylverCoinage" {
  topology = None   // --- NEW: no earlier case, including Kuhn poker's card-only state, went
                     // this far -- Kuhn still had `Site`-shaped... no, actually Kuhn also had no
                     // board (see games/kuhn-poker.sc, same finding, first noted there). Recorded
                     // here as confirmation, not a new discovery: two independent games in this
                     // batch both need "no topology" as a legitimate value, not an omission --
                     // worth promoting `topology = None` to a real, first-class option rather
                     // than an implicit default no earlier case exercised.
  players = 2

  state named: Set<Int> = empty   // unbounded: no static cap on how large this set can grow

  move Name(k: Int)
    if k >= 1 && !in_semigroup(k, named)
    then { set(named, insert(named, k)) }

  // --- The "cheap" end of the oracle-predicate spectrum this batch of four cases keeps landing
  // on (contrast games/sprouts.sc's `no_crossing` and games/ghost.sc's `is_prefix`): whether k is
  // representable as a non-negative combination of a finite generating set *does* reduce to an
  // ordinary `bounded_fixpoint` -- reachability over 0..k by repeatedly adding elements of
  // `named`, exactly the shape DESIGN.md's `bounded_fixpoint` was already designed for, with
  // `max_iters = k` as the static bound. Worth stating explicitly: not every oracle-shaped
  // predicate this batch needed turns out to be genuinely new machinery -- this one is a direct,
  // if non-obvious, instance of existing vocabulary.
  def in_semigroup(k: Int, generators: Set<Int>): Bool =
      fixpoint (reachable: Set<Int> = insert(empty, 0))
        step(r) = { for g in generators { for x in r { if x + g <= k { r := insert(r, x + g) } } } }
      until no_change(r) || max_iters(k)
      in member(reachable, k)

  // --- NEW: a "legal-but-suicidal" move -- naming 1 is always legal (1 is never in the
  // semigroup generated by any set of positive integers not already containing 1) but instantly
  // loses for whoever plays it. Every earlier case's `terminal`/`outcome` pair treated "the move
  // that ends the game" and "the move that was illegal" as the only two shapes a move could take;
  // this is a third shape, also needed by `games/ghost.sc`'s word-completion below. Modeled here
  // as an ordinary terminal condition plus an outcome that inspects *which* move was just played,
  // rather than as a special "suicidal" keyword -- no new grammar construct required, just a
  // pattern worth naming.
  terminal: Bool = member(named, 1)
  outcome: Outcome = if member(named, 1) then Win(opponent(mover)) else Draw   // Draw unreachable;
      // Sylver Coinage is a proper (always-decisive) game, but `outcome` still has to be total.

  // --- Open finding, deliberately unresolved (flagged, not solved, per this whole batch's
  // license): nothing in this file bounds how *long* the game can run before someone is forced to
  // name 1. Every earlier case in this corpus had a move-count bound derivable from local state --
  // Tak's from board cells plus reserves, Havannah's fixpoint from `count(group)`, even Kuhn
  // poker's from its fixed 3-ply betting structure. Sylver Coinage's finiteness (the game always
  // ends) is a real theorem (Hutchings), not a static bound readable off `state` the way
  // `bounded_fixpoint`'s `max_iters` always was -- this is the first case in the corpus where
  // "the game terminates" is a fact `terminal`'s author has to take on faith from game-theory
  // literature rather than something the grammar can express or check.
}
