[package]
name = "gdl"
version = "0.1.0"
edition = "2021"
description = "GDL (game description language) support"
license = "MIT OR Apache-2.0"

[dependencies]
game-core = { path = "../games/game-core" }

[dev-dependencies]
game-ttt = { path = "../games/ttt" }
game-ttt-gen = { path = "../games/ttt-gen" }
game-hex-gen = { path = "../games/hex-gen" }
game-hex3-gen = { path = "../games/hex3-gen" }
mcts = { path = "../mcts" }

[lints]
workspace = true
