[package]
name = "mcts-tests"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
mcts = { path = "../../crates/mcts" }
bitboard = { path = "../../crates/bitboard" }
game-core = { path = "../../games/game-core" }
game-othello = { path = "../../games/othello" }
game-atarigo = { path = "../../games/atarigo" }
game-breakthrough = { path = "../../games/breakthrough" }
game-knightthrough = { path = "../../games/knightthrough" }
game-druid = { path = "../../games/druid" }
game-ttt = { path = "../../games/ttt" }
game-connect4 = { path = "../../games/connect4" }
game-traffic-lights = { path = "../../games/traffic-lights" }
rustc-hash = "1.1.0"
rand = "0.8.5"
rand_core = "0.6.4"
rand_xorshift = "0.3.0"
sha2 = "0.10"
libc = "0.2"
rayon = "1.8.1"

[lints]
workspace = true
