//! The decision-move ludeme (Language Reference 8.1): `(move ...)`, a player's actual choice
//! among the legal moves generated by the rest of [`crate::ast::moves`]. It has around fifteen
//! distinct forms, one Java subclass each in Ludii; [`Decision`] gives each its own variant.

use crate::ast::common::{Between, From, IntOrRole, Piece, PlayerOrRole, To};
use crate::ast::direction::DirectionFunction;
use crate::ast::located::LBox;
use crate::ast::moves::Then;
use crate::ast::numeric::int::IntFunction;
use crate::ast::numeric::int_array::IntArrayFunction;
use crate::ast::numeric::range::RangeFunction;
use crate::ast::types::{RoleType, Walk, WhenType};

/// `moveMessageType` (8.1.2).
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum MoveMessageType {
    Propose,
    Vote,
}

/// `moveSimpleType` (8.1.3): decisions with no parameters besides `then`.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum MoveSimpleType {
    Pass,
    PlayCard,
}

/// `moveSiteType` (8.1.4).
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum MoveSiteType {
    Add,
    Claim,
}

/// One or more message strings, as used by [`Decision::Message`] and elsewhere.
#[derive(Debug, Clone, PartialEq)]
pub enum Messages {
    One(String),
    Many(Vec<String>),
}

/// The candidate suit(s) of `(move Set TrumpSuit ...)` (8.1.1).
#[derive(Debug, Clone, PartialEq)]
pub enum TrumpSuitChoice {
    Int(LBox<IntFunction>),
    Choices(LBox<IntArrayFunction>),
}

/// The next player set by `(move Set NextPlayer ...)` (8.1.1).
#[derive(Debug, Clone, PartialEq)]
pub enum NextPlayerChoice {
    Player(IntOrRole),
    Choices(LBox<IntArrayFunction>),
}

/// The new rotation(s) offered by `(move Set Rotation ...)` (8.1.1).
#[derive(Debug, Clone, PartialEq)]
pub enum RotationChoice {
    One(LBox<IntFunction>),
    Many(Vec<LBox<IntFunction>>),
}

/// `(move ...)` (8.1.1): a decision move -- the player's actual choice among the moves
/// generated by the rest of the rules.
#[derive(Debug, Clone, PartialEq)]
pub enum Decision {
    SwapPlayers {
        first: IntOrRole,
        second: IntOrRole,
        then: Option<Then>,
    },
    SwapPieces {
        first: Option<LBox<IntFunction>>,
        second: Option<LBox<IntFunction>>,
        then: Option<Then>,
    },
    Remove {
        site_type: Option<crate::ast::types::SiteType>,
        location: crate::ast::common::SiteOrRegion,
        level: Option<LBox<IntFunction>>,
        at: Option<WhenType>,
        count: Option<LBox<IntFunction>>,
        then: Option<Then>,
    },
    SetTrumpSuit {
        choice: TrumpSuitChoice,
        then: Option<Then>,
    },
    SetNextPlayer {
        next: NextPlayerChoice,
        then: Option<Then>,
    },
    SetRotation {
        to: Option<To>,
        directions: Option<RotationChoice>,
        previous: Option<bool>,
        next: Option<bool>,
        then: Option<Then>,
    },
    Step {
        from: Option<From>,
        direction: Option<LBox<DirectionFunction>>,
        to: To,
        stack: Option<bool>,
        then: Option<Then>,
    },
    Slide {
        from: Option<From>,
        track: Option<String>,
        direction: Option<LBox<DirectionFunction>>,
        between: Option<Between>,
        to: Option<To>,
        stack: Option<bool>,
        then: Option<Then>,
    },
    Shoot {
        piece: Piece,
        from: Option<From>,
        direction: Option<LBox<DirectionFunction>>,
        between: Option<Between>,
        to: Option<To>,
        then: Option<Then>,
    },
    Select {
        from: Option<From>,
        to: Option<To>,
        mover: Option<RoleType>,
        then: Option<Then>,
    },
    Message {
        kind: MoveMessageType,
        messages: Messages,
        then: Option<Then>,
    },
    Promote {
        site_type: Option<crate::ast::types::SiteType>,
        at: Option<LBox<IntFunction>>,
        piece: Piece,
        owner: Option<PlayerOrRole>,
        then: Option<Then>,
    },
    Simple(MoveSimpleType, Option<Then>),
    Leap {
        from: Option<From>,
        walks: Vec<Walk>,
        forward: Option<bool>,
        rotations: Option<bool>,
        to: To,
        then: Option<Then>,
    },
    Hop {
        from: Option<From>,
        direction: Option<LBox<DirectionFunction>>,
        between: Option<Between>,
        to: To,
        stack: Option<bool>,
        then: Option<Then>,
    },
    MovePiece {
        from: Option<From>,
        to: Option<To>,
        count: Option<LBox<IntFunction>>,
        copy: Option<bool>,
        stack: Option<bool>,
        mover: Option<RoleType>,
        then: Option<Then>,
    },
    Bet {
        who: PlayerOrRole,
        range: LBox<RangeFunction>,
        then: Option<Then>,
    },
    Site {
        kind: MoveSiteType,
        piece: Option<Piece>,
        to: To,
        count: Option<LBox<IntFunction>>,
        stack: Option<bool>,
        then: Option<Then>,
    },
}
