// @generated by `cargo run -p gdl --bin codegen -- gdl/style-c/sexpr/hex-11.gdls Hex` --
// do not edit by hand. Regenerate instead of patching -- see gdl/src/codegen/hex.rs.
//
// Hex, lowered from gdl/style-c/sexpr/hex-11.gdls via gdl::core::Program. Const-generic over board side
// `N` and `bitboard::Board<[u64; WORDS], Const<N>, Const<N>>`'s own `WORDS` parameter -- see a caller crate's
// `main.rs` (e.g. `games/hex-gen/src/main.rs`'s `dispatch_size!` macro) for how a concrete board
// size is picked at request time, the same pattern `games/gonnect` hand-writes for itself.

use bitboard::{Board, Const};
use game_core::display::{RectangularBoard, RectangularBoardDisplay};
use mcts::game::{Game, PlayerIndex};
use serde::{Deserialize, Serialize};
use std::fmt;

const NUM_PLAYERS: usize = 2;
const SEED: u64 = 0x49534419cd9c812a;

#[derive(Clone, Copy, PartialEq, Eq, Debug, Serialize, Deserialize)]
pub enum Player {
    P0,
    P1,
}

impl PlayerIndex for Player {
    fn to_index(&self) -> usize {
        match self {
            Player::P0 => 0,
            Player::P1 => 1,
        }
    }
}

impl Player {
    fn from_index(index: usize) -> Self {
        match index {
            0 => Player::P0,
            1 => Player::P1,
            _ => unreachable!(),
        }
    }

    fn next(self) -> Self {
        Player::from_index((self.to_index() + 1) % NUM_PLAYERS)
    }
}

/// The mover's stones (`board`, floodfilled from `edges[0]`) reach every remaining entry of
/// `edges` -- the Rust realization of `BoolExpr::Connects{ conn: Connectivity::Six }`, matching
/// `gdl::core::interp::eval_bool`'s own `Connects` arm but specialized once, at generation time,
/// to a direct `Board::flood6` call instead of `core::interp::bounded_fixpoint`'s general
/// iterate-to-a-fixpoint loop.
fn hex_connects<const N: usize, const WORDS: usize>(
    board: Board<[u64; WORDS], Const<N>, Const<N>>,
    edges: &[Board<[u64; WORDS], Const<N>, Const<N>>],
) -> bool {
    let [first, rest @ ..] = edges else {
        return false;
    };
    let flooded = board.flood6(*first);
    rest.iter().all(|&e| flooded.intersects(e))
}

fn side_east<const N: usize, const WORDS: usize>() -> Board<[u64; WORDS], Const<N>, Const<N>> {
    let mut b = Board::new_const();
    for c in 0..N {
        b.set_index(c * N + (N - 1));
    }
    b
}
fn side_north<const N: usize, const WORDS: usize>() -> Board<[u64; WORDS], Const<N>, Const<N>> {
    let mut b = Board::new_const();
    for c in 0..N {
        b.set_index((N - 1) * N + c);
    }
    b
}
fn side_south<const N: usize, const WORDS: usize>() -> Board<[u64; WORDS], Const<N>, Const<N>> {
    let mut b = Board::new_const();
    for c in 0..N {
        b.set_index(c);
    }
    b
}
fn side_west<const N: usize, const WORDS: usize>() -> Board<[u64; WORDS], Const<N>, Const<N>> {
    let mut b = Board::new_const();
    for c in 0..N {
        b.set_index(c * N);
    }
    b
}

#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, Serialize)]
pub struct Move(pub u8);

#[derive(Clone, Copy, PartialEq, Debug, Eq)]
pub struct Position<const N: usize, const WORDS: usize> {
    pub turn: Player,
    pub occupied: [Board<[u64; WORDS], Const<N>, Const<N>>; NUM_PLAYERS],
}

impl<const N: usize, const WORDS: usize> Default for Position<N, WORDS> {
    fn default() -> Self {
        Self::new()
    }
}

impl<const N: usize, const WORDS: usize> Position<N, WORDS> {
    pub fn new() -> Self {
        Self {
            turn: Player::P0,
            occupied: [Board::new_const(); NUM_PLAYERS],
        }
    }

    pub fn gen_moves(&self, actions: &mut Vec<Move>) {
        let legal = !(self.occupied[0] | self.occupied[1]);
        for s in legal {
            actions.push(Move(s as u8));
        }
    }

    pub fn apply(&mut self, m: Move) {
        self.occupied[self.turn.to_index()].set_index(m.0 as usize);
        self.turn = self.turn.next();
    }

    /// The player who moved most recently, and whether their move satisfied one of `program`'s
    /// end rules -- mirrors `core::interp::State::winner`, checking only the mover who just
    /// moved (per `core::EndRule`'s own doc comment), not every player unconditionally.
    pub fn winner(&self) -> Option<Player> {
        let last_mover = (self.turn.to_index() + NUM_PLAYERS - 1) % NUM_PLAYERS;
        let board = self.occupied[last_mover];
        let edges: &[Board<[u64; WORDS], Const<N>, Const<N>>] = match last_mover {
            0 => &[side_north::<N, WORDS>(), side_south::<N, WORDS>()],
            1 => &[side_west::<N, WORDS>(), side_east::<N, WORDS>()],
            _ => unreachable!(),
        };
        let won = { hex_connects(board, edges) };
        if won {
            Some(Player::from_index(last_mover))
        } else {
            None
        }
    }
}

/// Wraps `Position` with a hash recomputed from the raw board words on every `apply` -- see this
/// module's doc comment for why it's not an incrementally-maintained `LazyZobristTable` the way
/// `games/ttt-gen`/`games/hex3-gen` use (an array sized by `N` isn't expressible as a static item
/// on stable Rust). `WORDS` is always small (1-2) for every board size this backend targets, so
/// recomputing on every move is nowhere near a hot-path cost.
#[derive(Clone, Copy, PartialEq, Debug, Eq)]
pub struct HashedPosition<const N: usize, const WORDS: usize> {
    pub position: Position<N, WORDS>,
    pub hash: u64,
}

impl<const N: usize, const WORDS: usize> Default for HashedPosition<N, WORDS> {
    fn default() -> Self {
        Self::new()
    }
}

impl<const N: usize, const WORDS: usize> HashedPosition<N, WORDS> {
    pub fn new() -> Self {
        let position = Position::new();
        let hash = Self::compute_hash(&position);
        Self { position, hash }
    }

    /// FNV-1a over `position`'s occupied-board words plus whose turn it is -- deterministic and
    /// well-distributed, not cryptographic, matching `fnv1a`'s own role picking `SEED`.
    fn compute_hash(position: &Position<N, WORDS>) -> u64 {
        let mut h: u64 = SEED;
        for board in position.occupied {
            for w in board.words() {
                h ^= w;
                h = h.wrapping_mul(0x100000001b3);
            }
        }
        h ^= position.turn.to_index() as u64;
        h
    }

    fn apply(&mut self, m: Move) {
        self.position.apply(m);
        self.hash = Self::compute_hash(&self.position);
    }
}

#[derive(Debug, Clone)]
pub struct Hex<const N: usize, const WORDS: usize>;

impl<const N: usize, const WORDS: usize> Game for Hex<N, WORDS> {
    type S = HashedPosition<N, WORDS>;
    type A = Move;
    type P = Player;

    fn generate_actions(state: &Self::S, actions: &mut Vec<Self::A>) {
        state.position.gen_moves(actions);
    }

    fn apply(mut state: Self::S, m: &Self::A) -> Self::S {
        state.apply(*m);
        state
    }

    fn is_terminal(state: &Self::S) -> bool {
        if state.position.winner().is_some() {
            return true;
        }
        let mut actions = Vec::new();
        Self::generate_actions(state, &mut actions);
        actions.is_empty()
    }

    fn winner(state: &Self::S) -> Option<Self::P> {
        state.position.winner()
    }

    fn player_to_move(state: &Self::S) -> Self::P {
        state.position.turn
    }

    fn num_players() -> usize {
        NUM_PLAYERS
    }

    fn zobrist_hash(state: &Self::S) -> u64 {
        state.hash
    }

    fn notation(_state: &Self::S, m: &Self::A) -> String {
        format!("({}, {})", m.0 as usize % N, m.0 as usize / N)
    }
}

impl<const N: usize, const WORDS: usize> RectangularBoard for HashedPosition<N, WORDS> {
    const NUM_DISPLAY_ROWS: usize = N;
    const NUM_DISPLAY_COLS: usize = N;

    fn display_char_at(&self, row: usize, col: usize) -> char {
        let site = row * N + col;
        for p in 0..NUM_PLAYERS {
            if self.position.occupied[p].get_index(site) {
                return (b'A' + p as u8) as char;
            }
        }
        '.'
    }
}

impl<const N: usize, const WORDS: usize> fmt::Display for HashedPosition<N, WORDS> {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        RectangularBoardDisplay(self).fmt(f)
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use mcts::util::random_play;

    #[test]
    fn random_playouts_terminate() {
        random_play::<Hex<11, 2>>();
    }
}
