[package]
name = "game-focus"
version = "0.1.0"
edition = "2021"
publish = false

[lib]
name = "game_focus"

[[bin]]
name = "game-focus-2p"
path = "src/bin/focus_2p.rs"

[[bin]]
name = "game-focus-3p"
path = "src/bin/focus_3p.rs"

[[bin]]
name = "game-focus-4p"
path = "src/bin/focus_4p.rs"

[dependencies]
mcts = { path = "../../mcts" }
mcts-tune = { path = "../../mcts-tune" }
game-host = { path = "../../game-host" }
serde = { version = "1", features = ["derive"] }
serde_json = "1"

[dev-dependencies]
rand = { version = "0.8.5", features = ["small_rng"] }

[lints]
workspace = true
