[package]
name = "game-ttt"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
mcts = { path = "../../crates/mcts" }
mcts-tune = { path = "../../crates/mcts-tune" }
game-core = { path = "../game-core" }
game-host = { path = "../../apps/game-host" }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
proptest = "1.4.0"
rand = "0.8"

[dev-dependencies]
rustc-hash = "1.1.0"

[lints]
workspace = true
