// @generated by `cargo run -p gdl --bin codegen -- gdl/style-c/sexpr/hex.gdls Hex` --
// do not edit by hand. Regenerate instead of patching -- see gdl/src/codegen/hex.rs.
//
// Hex, lowered from gdl/style-c/sexpr/hex.gdls via gdl::core::Program.

use game_core::bitboard::BitBoard;
use game_core::display::{RectangularBoard, RectangularBoardDisplay};
use mcts::game::{Game, PlayerIndex};
use mcts::zobrist::LazyZobristTable;
use serde::{Deserialize, Serialize};
use std::fmt;

const SIDE: usize = 3;
const NUM_PLAYERS: usize = 2;

type Board = BitBoard<3, 3>;

#[derive(Clone, Copy, PartialEq, Eq, Debug, Serialize, Deserialize)]
pub enum Player {
    P0,
    P1,
}

impl PlayerIndex for Player {
    fn to_index(&self) -> usize {
        match self {
            Player::P0 => 0,
            Player::P1 => 1,
        }
    }
}

impl Player {
    fn from_index(index: usize) -> Self {
        match index {
            0 => Player::P0,
            1 => Player::P1,
            _ => unreachable!(),
        }
    }

    fn next(self) -> Self {
        Player::from_index((self.to_index() + 1) % NUM_PLAYERS)
    }
}

/// The mover's stones (`board`, floodfilled from `edges[0]`) reach every remaining entry of
/// `edges` -- the Rust realization of `BoolExpr::Connects{ conn: Connectivity::Six }`, matching
/// `gdl::core::interp::eval_bool`'s own `Connects` arm but specialized once, at generation time,
/// to a direct `BitBoard::flood6` call instead of `core::interp::bounded_fixpoint`'s general
/// iterate-to-a-fixpoint loop.
fn hex_connects(board: Board, edges: &[Board]) -> bool {
    let [first, rest @ ..] = edges else {
        return false;
    };
    let flooded = board.flood6(*first);
    rest.iter().all(|&e| flooded.intersects(e))
}

#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, Serialize)]
pub struct Move(pub u8);

#[derive(Clone, Copy, PartialEq, Debug, Eq)]
pub struct Position {
    pub turn: Player,
    pub occupied: [Board; NUM_PLAYERS],
}

impl Default for Position {
    fn default() -> Self {
        Self::new()
    }
}

impl Position {
    pub fn new() -> Self {
        Self {
            turn: Player::P0,
            occupied: [Board::EMPTY; NUM_PLAYERS],
        }
    }

    pub fn gen_moves(&self, actions: &mut Vec<Move>) {
        let legal = !(self.occupied[0] | self.occupied[1]);
        for s in legal {
            actions.push(Move(s as u8));
        }
    }

    pub fn apply(&mut self, m: Move) {
        self.occupied[self.turn.to_index()].set(m.0 as usize);
        self.turn = self.turn.next();
    }

    /// The player who moved most recently, and whether their move satisfied one of `program`'s
    /// end rules -- mirrors `core::interp::State::winner`, checking only the mover who just
    /// moved (per `core::EndRule`'s own doc comment), not every player unconditionally.
    pub fn winner(&self) -> Option<Player> {
        let last_mover = (self.turn.to_index() + NUM_PLAYERS - 1) % NUM_PLAYERS;
        let board = self.occupied[last_mover];
        let edges: &[Board] = match last_mover {
            0 => &[Board::new(0b111000000), Board::new(0b111)],
            1 => &[Board::new(0b1001001), Board::new(0b100100100)],
            _ => unreachable!(),
        };
        let won = { hex_connects(board, edges) };
        if won {
            Some(Player::from_index(last_mover))
        } else {
            None
        }
    }
}

const NUM_SITES: usize = SIDE * SIDE;
const NUM_HASHES: usize = NUM_SITES * NUM_PLAYERS;
static HASHES: LazyZobristTable<NUM_HASHES> = LazyZobristTable::new(0x49534419cd9c812a);

/// Wraps `Position` with an incrementally-maintained zobrist hash -- unlike `games/ttt`'s own
/// `HashedPosition`, this doesn't track a symmetry-aware hash per symmetry (that's a hand
/// optimization `Program` has no way to request yet, not part of Core IR's own semantics).
#[derive(Clone, Copy, PartialEq, Debug, Eq)]
pub struct HashedPosition {
    pub position: Position,
    pub hash: u64,
}

impl Default for HashedPosition {
    fn default() -> Self {
        Self::new()
    }
}

impl HashedPosition {
    pub fn new() -> Self {
        Self {
            position: Position::new(),
            hash: 0,
        }
    }

    fn apply(&mut self, m: Move) {
        self.hash ^= HASHES.hash((m.0 as usize) * NUM_PLAYERS + self.position.turn.to_index());
        self.position.apply(m);
    }
}

#[derive(Debug, Clone)]
pub struct Hex;

impl Game for Hex {
    type S = HashedPosition;
    type A = Move;
    type P = Player;

    fn generate_actions(state: &Self::S, actions: &mut Vec<Self::A>) {
        state.position.gen_moves(actions);
    }

    fn apply(mut state: Self::S, m: &Self::A) -> Self::S {
        state.apply(*m);
        state
    }

    fn is_terminal(state: &Self::S) -> bool {
        if state.position.winner().is_some() {
            return true;
        }
        let mut actions = Vec::new();
        Self::generate_actions(state, &mut actions);
        actions.is_empty()
    }

    fn winner(state: &Self::S) -> Option<Self::P> {
        state.position.winner()
    }

    fn player_to_move(state: &Self::S) -> Self::P {
        state.position.turn
    }

    fn num_players() -> usize {
        NUM_PLAYERS
    }

    fn zobrist_hash(state: &Self::S) -> u64 {
        state.hash
    }

    fn notation(_state: &Self::S, m: &Self::A) -> String {
        format!("({}, {})", m.0 as usize % SIDE, m.0 as usize / SIDE)
    }
}

impl RectangularBoard for HashedPosition {
    const NUM_DISPLAY_ROWS: usize = SIDE;
    const NUM_DISPLAY_COLS: usize = SIDE;

    fn display_char_at(&self, row: usize, col: usize) -> char {
        let site = row * SIDE + col;
        for p in 0..NUM_PLAYERS {
            if self.position.occupied[p].get(site) {
                return (b'A' + p as u8) as char;
            }
        }
        '.'
    }
}

impl fmt::Display for HashedPosition {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        RectangularBoardDisplay(self).fmt(f)
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use mcts::util::random_play;

    #[test]
    fn random_playouts_terminate() {
        random_play::<Hex>();
    }
}
