//! Raw FFI over Homebrew's already-built `mlx`/`mlx-c` dylibs, generated by
//! `bindgen` straight from the installed headers. This deliberately does
//! *not* vendor or build MLX from source the way `mlx-rs`'s own `mlx-sys`
//! crate (and `mlxrs-sys`) do: both of those compile MLX's Metal shaders via
//! a `metal` compiler binary that requires `xcodebuild -downloadComponent
//! MetalToolchain`, which most machines won't have installed. Homebrew's
//! `mlx` (`brew install mlx`) and `mlx-c` (`brew install mlx-c`) formulae
//! ship fully-built dylibs plus a precompiled `mlx.metallib`, so linking
//! straight against them needs no Metal shader compilation at all.
//!
//! Paths default to Homebrew's standard opt-prefix layout and can be
//! overridden with `MLX_C_PREFIX`/`MLX_PREFIX` for a non-Homebrew install.

use std::path::PathBuf;

fn prefix(env_var: &str, default: &str) -> PathBuf {
    std::env::var_os(env_var)
        .map(PathBuf::from)
        .unwrap_or_else(|| PathBuf::from(default))
}

fn main() {
    let mlxc = prefix("MLX_C_PREFIX", "/opt/homebrew/opt/mlx-c");
    let mlx = prefix("MLX_PREFIX", "/opt/homebrew/opt/mlx");

    let header = mlxc.join("include/mlx/c/mlx.h");
    if !header.exists() {
        panic!(
            "mlx-sys: {} not found. Install Homebrew's mlx-c (`brew install mlx-c`), or point \
             MLX_C_PREFIX at an mlx-c install (expects <prefix>/include/mlx/c/mlx.h and \
             <prefix>/lib/libmlxc.dylib).",
            header.display()
        );
    }

    println!("cargo:rustc-link-search=native={}", mlxc.join("lib").display());
    println!("cargo:rustc-link-search=native={}", mlx.join("lib").display());
    println!("cargo:rustc-link-lib=dylib=mlxc");
    println!("cargo:rustc-link-lib=dylib=mlx");
    println!("cargo:rustc-link-arg=-Wl,-rpath,{}", mlxc.join("lib").display());
    println!("cargo:rustc-link-arg=-Wl,-rpath,{}", mlx.join("lib").display());

    let bindings = bindgen::Builder::default()
        .header(header.to_string_lossy())
        .clang_arg(format!("-I{}", mlxc.join("include").display()))
        .clang_arg(format!("-I{}", mlx.join("include").display()))
        .clang_arg("-x")
        .clang_arg("c")
        .allowlist_function("mlx_.*")
        .allowlist_type("mlx_.*")
        .generate()
        .expect("mlx-sys: bindgen failed over mlx-c headers");

    let out = std::env::var("OUT_DIR").unwrap();
    bindings
        .write_to_file(format!("{out}/bindings.rs"))
        .expect("mlx-sys: failed to write bindings.rs");

    println!("cargo:rerun-if-env-changed=MLX_C_PREFIX");
    println!("cargo:rerun-if-env-changed=MLX_PREFIX");
}
