[package]
name = "game-connect4"
version = "0.1.0"
edition = "2021"
publish = false

[lib]
name = "game_connect4"

[[bin]]
name = "game-connect4"
path = "src/main.rs"

[dependencies]
mcts = { path = "../../crates/mcts" }
game-core = { path = "../game-core" }
bitboard = { path = "../../crates/bitboard" }
serde = { version = "1", features = ["derive"] }
rand = { version = "0.8.5", features = ["small_rng"] }
rayon = "1.8.1"

[lints]
workspace = true
