// @generated by `cargo run -p gdl --bin codegen -- gdl/style-c/sexpr/tic-tac-toe.gdls TicTacToe` --
// do not edit by hand. Regenerate instead of patching -- see gdl/src/codegen/rect.rs.
//
// Tic-Tac-Toe, lowered from gdl/style-c/sexpr/tic-tac-toe.gdls via gdl::core::Program.

use game_core::bitboard::BitBoard;
use game_core::display::{RectangularBoard, RectangularBoardDisplay};
use mcts::game::{Game, PlayerIndex};
use mcts::zobrist::LazyZobristTable;
use serde::{Deserialize, Serialize};
use std::fmt;

const ROWS: usize = 3;
const COLS: usize = 3;
const NUM_PLAYERS: usize = 2;

type Board = BitBoard<3, 3>;

#[derive(Clone, Copy, PartialEq, Eq, Debug, Serialize, Deserialize)]
pub enum Player {
    P0,
    P1,
}

impl PlayerIndex for Player {
    fn to_index(&self) -> usize {
        match self {
            Player::P0 => 0,
            Player::P1 => 1,
        }
    }
}

impl Player {
    fn from_index(index: usize) -> Self {
        match index {
            0 => Player::P0,
            1 => Player::P1,
            _ => unreachable!(),
        }
    }

    fn next(self) -> Self {
        Player::from_index((self.to_index() + 1) % NUM_PLAYERS)
    }
}

#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, Serialize)]
pub struct Move(pub u8);

#[derive(Clone, Copy, PartialEq, Debug, Eq)]
pub struct Position {
    pub turn: Player,
    pub occupied: [Board; NUM_PLAYERS],
}

impl Default for Position {
    fn default() -> Self {
        Self::new()
    }
}

impl Position {
    pub fn new() -> Self {
        Self {
            turn: Player::P0,
            occupied: [Board::EMPTY; NUM_PLAYERS],
        }
    }

    pub fn gen_moves(&self, actions: &mut Vec<Move>) {
        let legal = !(self.occupied[0] | self.occupied[1]);
        for s in legal {
            actions.push(Move(s as u8));
        }
    }

    pub fn apply(&mut self, m: Move) {
        self.occupied[self.turn.to_index()].set(m.0 as usize);
        self.turn = self.turn.next();
    }

    /// The player who moved most recently, and whether their move satisfied one of `program`'s
    /// end rules -- mirrors `core::interp::State::winner`, checking only the mover who just
    /// moved (per `core::EndRule`'s own doc comment), not every player unconditionally.
    pub fn winner(&self) -> Option<Player> {
        let last_mover = (self.turn.to_index() + NUM_PLAYERS - 1) % NUM_PLAYERS;
        let board = self.occupied[last_mover];
        let won = {
            (Board::new(0b111)).is_subset(board)
                || (Board::new(0b111000)).is_subset(board)
                || (Board::new(0b111000000)).is_subset(board)
                || (Board::new(0b1001001)).is_subset(board)
                || (Board::new(0b10010010)).is_subset(board)
                || (Board::new(0b100100100)).is_subset(board)
                || (Board::new(0b100010001)).is_subset(board)
                || (Board::new(0b1010100)).is_subset(board)
        };
        if won {
            Some(Player::from_index(last_mover))
        } else {
            None
        }
    }
}

const NUM_SITES: usize = ROWS * COLS;
const NUM_HASHES: usize = NUM_SITES * NUM_PLAYERS;
static HASHES: LazyZobristTable<NUM_HASHES> = LazyZobristTable::new(0x786bf8d4422fae5f);

/// Wraps `Position` with an incrementally-maintained zobrist hash -- unlike `games/ttt`'s own
/// `HashedPosition`, this doesn't track a D4-symmetry-aware hash per symmetry (that's a
/// `Rect`-square-specific hand optimization `Program` has no way to request yet, not part of
/// Core IR's own semantics).
#[derive(Clone, Copy, PartialEq, Debug, Eq)]
pub struct HashedPosition {
    pub position: Position,
    pub hash: u64,
}

impl Default for HashedPosition {
    fn default() -> Self {
        Self::new()
    }
}

impl HashedPosition {
    pub fn new() -> Self {
        Self {
            position: Position::new(),
            hash: 0,
        }
    }

    fn apply(&mut self, m: Move) {
        self.hash ^= HASHES.hash((m.0 as usize) * NUM_PLAYERS + self.position.turn.to_index());
        self.position.apply(m);
    }
}

#[derive(Debug, Clone)]
pub struct TicTacToe;

impl Game for TicTacToe {
    type S = HashedPosition;
    type A = Move;
    type P = Player;

    fn generate_actions(state: &Self::S, actions: &mut Vec<Self::A>) {
        state.position.gen_moves(actions);
    }

    fn apply(mut state: Self::S, m: &Self::A) -> Self::S {
        state.apply(*m);
        state
    }

    fn is_terminal(state: &Self::S) -> bool {
        if state.position.winner().is_some() {
            return true;
        }
        let mut actions = Vec::new();
        Self::generate_actions(state, &mut actions);
        actions.is_empty()
    }

    fn winner(state: &Self::S) -> Option<Self::P> {
        state.position.winner()
    }

    fn player_to_move(state: &Self::S) -> Self::P {
        state.position.turn
    }

    fn num_players() -> usize {
        NUM_PLAYERS
    }

    fn zobrist_hash(state: &Self::S) -> u64 {
        state.hash
    }

    fn notation(_state: &Self::S, m: &Self::A) -> String {
        format!("({}, {})", m.0 as usize % COLS, m.0 as usize / COLS)
    }
}

impl RectangularBoard for HashedPosition {
    const NUM_DISPLAY_ROWS: usize = ROWS;
    const NUM_DISPLAY_COLS: usize = COLS;

    fn display_char_at(&self, row: usize, col: usize) -> char {
        let site = row * COLS + col;
        for p in 0..NUM_PLAYERS {
            if self.position.occupied[p].get(site) {
                return (b'A' + p as u8) as char;
            }
        }
        '.'
    }
}

impl fmt::Display for HashedPosition {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        RectangularBoardDisplay(self).fmt(f)
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use mcts::util::random_play;

    #[test]
    fn random_playouts_terminate() {
        random_play::<TicTacToe>();
    }
}
